name: Release by tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GH_PAT }}
